#!/usr/bin/env python3
"""Generate synthetic DEE training samples using prompt templates + LLM-free text construction.

Strategy: For each of the 39 DEE profiles at 3 intensity levels, generate 30-50 text samples
that exhibit the behavioral markers for that profile. This is NOT LLM-generated — it uses
the lexicon patterns and behavioral markers to construct examples programmatically.

This avoids model contamination: training data is hand-crafted from the taxonomy's
behavioral markers, not generated by the same type of model being classified.

Usage:
    PYTHONPATH=src python3 scripts/generate_training_data.py --count 50 --output /tmp/dee_training_samples.jsonl
"""

import argparse
import json
import random
import sys
import os

# Add src to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from netrun.dee.lexicon import DEE_LEXICONS, LexiconEntry
from netrun.dee.taxonomy import DEE_PROFILES, DEE_PROFILES_LIST


# --- Sentence templates by register and intensity ---
# Each template has {pattern} slots that get filled with lexicon entries.

# Professional register templates (workplace/technical context)
PROFESSIONAL_TEMPLATES = {
    'subtle': [
        "The latest report shows {p1}. We should review this in the next sync.",
        "I noticed {p1} in the metrics dashboard. Worth keeping an eye on.",
        "Per the retrospective, {p1}. Let me know your thoughts.",
        "Quick update: {p1}. No action needed right now.",
        "FYI — {p1}. Adding to the backlog for discussion.",
        "The team mentioned {p1} during standup today.",
        "Looking at the data, it seems like {p1}.",
        "Flagging for visibility: {p1}. Not urgent.",
        "Based on the Q3 numbers, {p1}.",
        "The client mentioned {p1} in their feedback.",
    ],
    'moderate': [
        "{p1}. {p2}. We need to discuss this at the next meeting.",
        "I want to flag that {p1}. Additionally, {p2}.",
        "Two things from today's review: {p1}, and {p2}.",
        "The sprint retro surfaced some concerns. {p1}. {p2}.",
        "After reviewing the deployment, {p1}. Also, {p2}.",
        "This quarter's results show {p1}. On a related note, {p2}.",
        "The stakeholder call raised issues: {p1}. Furthermore, {p2}.",
        "Based on the latest audit, {p1}. {p2}. Let's sync.",
        "During the post-mortem, {p1}. The team also noted {p2}.",
        "Key takeaway from the review: {p1}. Also worth noting — {p2}.",
    ],
    'strong': [
        "{p1}. {p2}. {p3}. This needs immediate attention.",
        "To be direct: {p1}. {p2}. {p3}.",
        "I need to escalate this. {p1}. {p2}. {p3}.",
        "This is becoming a pattern: {p1}. {p2}. {p3}.",
        "Let me be clear about the situation. {p1}. {p2}. {p3}.",
        "The situation is serious. {p1}. {p2}. {p3}. We cannot delay.",
        "Multiple issues converging here. {p1}. {p2}. {p3}.",
        "Summary of the problem: {p1}. Context: {p2}. Impact: {p3}.",
        "This has been raised before. {p1}. {p2}. {p3}.",
        "{p1}. Beyond that, {p2}. And to make matters worse, {p3}.",
    ],
}

# Casual register templates (everyday/informal context)
CASUAL_TEMPLATES = {
    'subtle': [
        "Hey, just wanted to mention that {p1}.",
        "So, {p1}. Thought you should know.",
        "Not a big deal, but {p1}.",
        "Random thought — {p1}.",
        "Just FYI, {p1}.",
        "Was thinking about this and {p1}.",
        "Quick note: {p1}.",
        "Heads up that {p1}.",
    ],
    'moderate': [
        "{p1}. Also, {p2}. What do you think?",
        "Okay so {p1}. And honestly, {p2}.",
        "Been meaning to say — {p1}. Plus {p2}.",
        "{p1}. {p2}. Let me know how you want to handle it.",
        "Two things on my mind: {p1}. And {p2}.",
        "So here's the deal: {p1}. On top of that, {p2}.",
    ],
    'strong': [
        "{p1}. {p2}. {p3}. Seriously.",
        "Look — {p1}. {p2}. {p3}.",
        "{p1}. And {p2}. Not to mention {p3}.",
        "I need to vent. {p1}. {p2}. {p3}.",
        "{p1}. {p2}. {p3}. I can't keep ignoring this.",
        "This is getting out of hand. {p1}. {p2}. {p3}.",
    ],
}

# --- Phrase expansions: convert lexicon patterns into natural sentence fragments ---

def _expand_pattern(entry: LexiconEntry) -> str:
    """Turn a lexicon entry into a natural sentence fragment."""
    p = entry.pattern

    if entry.is_regex:
        # Convert regex patterns to concrete examples
        REGEX_EXPANSIONS = {
            r'!{2,}': 'the results were incredible!!',
            r'[A-Z]{3,}\b': 'this is CRITICAL',
            r'[FfDd]\s*grade': 'we got a D grade on this',
            r'flagged\s+\d+\s*times?': 'this has been flagged 3 times',
            r'\?{2,}': 'how did this happen??',
            r'\d+\s*days?\s*stale': 'the data is 10 days stale',
            r'\d+\s*days?\s*since': 'it has been 14 days since the last update',
            r';\)': 'you know what I mean ;)',
            r':\)': 'sounds good :)',
        }
        return REGEX_EXPANSIONS.get(p, f'the {p} pattern was detected')

    # For plain keywords/phrases, wrap in plausible context fragments
    if entry.category == 'keyword':
        KEYWORD_FRAMES = [
            f"the situation is {p}",
            f"this feels {p}",
            f"I would describe it as {p}",
            f"the word that comes to mind is {p}",
            f"things are looking {p}",
            f"the response was {p}",
            f"it was genuinely {p}",
            f"what stands out is how {p} this is",
        ]
        return random.choice(KEYWORD_FRAMES)

    # Phrases can often stand alone or with light framing
    PHRASE_FRAMES = [
        f"{p}",
        f"we {p}",
        f"I {p}",
        f"the team {p}",
        f"it's clear that {p}",
        f"as it turns out, {p}",
    ]
    return random.choice(PHRASE_FRAMES)


def _get_lexicon_fragments(profile_id: str, count: int) -> list[str]:
    """Get N random expanded lexicon fragments for a profile."""
    entries = DEE_LEXICONS.get(profile_id, [])
    if not entries:
        return []

    # Weight selection by entry weight (higher weight = more likely to be selected)
    weights = [e.weight for e in entries]
    selected = random.choices(entries, weights=weights, k=count)
    return [_expand_pattern(e) for e in selected]


# --- Multi-label combination templates ---

MULTI_LABEL_COMBOS = [
    # (profile_ids, template)
    (['DEE-03', 'DEE-24'], "CRITICAL: {p1}. {p2}. This recurring failure is exactly why we need to pivot."),
    (['DEE-03', 'DEE-24'], "{p1}. {p2}. How many times do we need to escalate this?"),
    (['DEE-04', 'DEE-24'], "ALERT: {p1}. {p2}. If we don't act now, we lose the window."),
    (['DEE-04', 'DEE-24'], "{p1}. {p2}. The deadline is tomorrow and we have no fallback."),
    (['DEE-01', 'DEE-14'], "{p1}. {p2}. The team should be proud of what we built."),
    (['DEE-01', 'DEE-14'], "Outstanding results — {p1}. And {p2}. This is what delivery looks like."),
    (['DEE-02', 'DEE-19'], "{p1}. {p2}. I think we have to accept where we are."),
    (['DEE-02', 'DEE-33'], "{p1}. {p2}. I keep thinking about how it could have been different."),
    (['DEE-15', 'DEE-34'], "{p1}. {p2}. What if we tried a completely different approach?"),
    (['DEE-15', 'DEE-21'], "{p1}. {p2}. The architecture here is genuinely elegant."),
    (['DEE-07', 'DEE-27'], "{p1}. {p2}. Everything is running smoothly."),
    (['DEE-12', 'DEE-09'], "{p1}. {p2}. I really appreciate what everyone has been through."),
    (['DEE-13', 'DEE-06'], "{p1}. {p2}. This should never have been approved."),
    (['DEE-18', 'DEE-24'], "{p1}. {p2}. We push through regardless of the obstacles."),
    (['DEE-10', 'DEE-32'], "{p1}. {p2}. I should have caught this earlier."),
    (['DEE-26', 'DEE-31'], "{p1}. {p2}. Nothing seems to make a difference anymore."),
    (['DEE-29', 'DEE-25'], "{p1}. {p2}. Stay vigilant — the threat surface just expanded."),
    (['DEE-08', 'DEE-01'], "{p1}. {p2}. The launch is going to be something special."),
    (['DEE-22', 'DEE-01'], "{p1}. {p2}. Honestly, this sprint was actually fun."),
    (['DEE-20', 'DEE-04'], "{p1}. {p2}. Something about this vendor's claims doesn't add up."),
    (['DEE-03', 'DEE-13'], "{p1}. {p2}. I've explained this three times now."),
    (['DEE-04', 'DEE-02'], "{p1}. {p2}. The situation is dire and the numbers confirm it."),
    (['DEE-34', 'DEE-18'], "{p1}. {p2}. This is the breakthrough we've been waiting for."),
    (['DEE-16', 'DEE-19'], "{p1}. {p2}. Same standup, same issues, every week."),
]


def _intensity_to_level(intensity: float) -> str:
    if intensity <= 1.0:
        return 'subtle'
    elif intensity <= 2.0:
        return 'moderate'
    return 'strong'


def generate_single_label_sample(profile_id: str, intensity_level: str) -> dict:
    """Generate one training sample for a single DEE profile."""
    register = random.choice(['professional', 'casual'])
    templates = PROFESSIONAL_TEMPLATES if register == 'professional' else CASUAL_TEMPLATES
    template_list = templates[intensity_level]
    template = random.choice(template_list)

    # Count how many pattern slots are in the template
    slot_count = template.count('{p')
    fragments = _get_lexicon_fragments(profile_id, max(slot_count, 1))

    # Fill slots
    text = template
    for i, frag in enumerate(fragments[:slot_count], 1):
        text = text.replace(f'{{p{i}}}', frag, 1)

    # Intensity value: subtle=0.5-1.0, moderate=1.0-2.0, strong=2.0-3.0
    intensity_ranges = {
        'subtle': (0.5, 1.0),
        'moderate': (1.0, 2.0),
        'strong': (2.0, 3.0),
    }
    lo, hi = intensity_ranges[intensity_level]
    intensity = round(random.uniform(lo, hi), 1)

    return {
        'text': text,
        'labels': {profile_id: intensity},
        'intensity_level': intensity_level,
    }


def generate_multi_label_sample(combo_idx: int) -> dict:
    """Generate a multi-label sample from predefined combinations."""
    profile_ids, template = MULTI_LABEL_COMBOS[combo_idx]

    # Get fragments for each profile
    all_fragments = []
    for pid in profile_ids:
        frags = _get_lexicon_fragments(pid, 2)
        all_fragments.extend(frags)

    random.shuffle(all_fragments)

    # Fill template slots
    text = template
    slot_count = template.count('{p')
    for i, frag in enumerate(all_fragments[:slot_count], 1):
        text = text.replace(f'{{p{i}}}', frag, 1)

    # Assign intensities — the primary is stronger
    labels = {}
    for i, pid in enumerate(profile_ids):
        if i == 0:
            labels[pid] = round(random.uniform(1.5, 3.0), 1)
        else:
            labels[pid] = round(random.uniform(0.5, 2.0), 1)

    return {
        'text': text,
        'labels': labels,
        'intensity_level': 'strong' if max(labels.values()) > 2.0 else 'moderate',
    }


def generate_dataset(samples_per_profile: int = 50, seed: int = 42) -> list[dict]:
    """Generate the full synthetic training dataset.

    For each of the 39 profiles:
    - ~1/3 subtle intensity
    - ~1/3 moderate intensity
    - ~1/3 strong intensity

    Plus multi-label combination samples.

    Args:
        samples_per_profile: Number of single-label samples per profile.
        seed: Random seed for reproducibility.

    Returns:
        List of training sample dicts.
    """
    random.seed(seed)
    samples = []

    # Single-label samples
    for profile in DEE_PROFILES_LIST:
        subtle_count = samples_per_profile // 3
        moderate_count = samples_per_profile // 3
        strong_count = samples_per_profile - subtle_count - moderate_count

        for _ in range(subtle_count):
            samples.append(generate_single_label_sample(profile.id, 'subtle'))
        for _ in range(moderate_count):
            samples.append(generate_single_label_sample(profile.id, 'moderate'))
        for _ in range(strong_count):
            samples.append(generate_single_label_sample(profile.id, 'strong'))

    # Multi-label samples: 5 samples per combination
    for combo_idx in range(len(MULTI_LABEL_COMBOS)):
        for _ in range(5):
            samples.append(generate_multi_label_sample(combo_idx))

    random.shuffle(samples)
    return samples


def main():
    parser = argparse.ArgumentParser(description='Generate synthetic DEE training data')
    parser.add_argument('--count', type=int, default=50,
                        help='Samples per profile (default: 50)')
    parser.add_argument('--output', type=str, default='/tmp/dee_training_samples.jsonl',
                        help='Output JSONL file path')
    parser.add_argument('--seed', type=int, default=42,
                        help='Random seed for reproducibility')
    args = parser.parse_args()

    samples = generate_dataset(samples_per_profile=args.count, seed=args.seed)

    # Write JSONL
    with open(args.output, 'w') as f:
        for sample in samples:
            f.write(json.dumps(sample) + '\n')

    # Summary stats
    single_label = sum(1 for s in samples if len(s['labels']) == 1)
    multi_label = sum(1 for s in samples if len(s['labels']) > 1)

    # Per-profile counts
    profile_counts: dict[str, int] = {}
    for s in samples:
        for pid in s['labels']:
            profile_counts[pid] = profile_counts.get(pid, 0) + 1

    print(f"Generated {len(samples)} training samples")
    print(f"  Single-label: {single_label}")
    print(f"  Multi-label:  {multi_label}")
    print(f"  Profiles covered: {len(profile_counts)}/39")
    print(f"  Output: {args.output}")

    # Intensity distribution
    levels = {'subtle': 0, 'moderate': 0, 'strong': 0}
    for s in samples:
        levels[s['intensity_level']] += 1
    print(f"  Intensity distribution: {levels}")


if __name__ == '__main__':
    main()
